version: '3.3'
services:
  orthanc:
    image: jodogne/orthanc
    ports:
      - "8042:8042"
    volumes:
      - ./orthanc.json:/etc/orthanc/orthanc.json:ro
    environment:
      - ORTHANC__NAME=Orthanc
      - ORTHANC__AUTHENTICATION_ENABLED=false
      - ORTHANC__DICOM_SERVER_ENABLED=true
      - ORTHANC__DICOM_MODALITIES_IN_DATABASE=true
      - ORTHANC__DICOM_WEB_ENABLED=true
      - ORTHANC__HTTP_PORT=8042
      - ORTHANC__REMOTE_ACCESS_ALLOWED=true
      - ORTHANC__CORS_ENABLED=true
      - ORTHANC__CORS_ALLOWED_ORIGINS=http://localhost:5174
      - ORTHANC__HTTP_ACCESS_CONTROL_ALLOW_ORIGIN=http://localhost:5174
      - ORTHANC__HTTP_ACCESS_CONTROL_ALLOW_METHODS=GET,POST,PUT,DELETE,OPTIONS
      - ORTHANC__HTTP_ACCESS_CONTROL_ALLOW_HEADERS=Content-Type,Authorization,Accept,X-Requested-With
      - ORTHANC__HTTP_ACCESS_CONTROL_ALLOW_CREDENTIALS=true
